# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1246a2607b81a2d7face05fd99bdb908404fa20e0167ad46099fd4c869b0037b59ff488d115a634675aa699efddcf5be119c0fa5fa63997a413c08c7da83a904

test:
  secret_key_base: a885fcbe93aba055fb6e02454f8f3a606fdfb3161e2f26abe8253cff5fb9eaf0cd64a3cf626efddb5964044047a54a26b17b58443522ad3aadcdcee212c5e06b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
